### ISSUE TITLE
Live demo issues

### ISSUE THREAD

**Issue by neurolabusc** [Twinklebear/webgpu-volume-raycaster#3]
When I attempt to run the live demo on Windows 10 with NVidia GTX770 GPU and Chrome Version 112.0.5615.50 I get an error in the developer tools console even though other WebGPU demos run:
```
Uncaught (in promise) TypeError: i.getCompilationInfo is not a function
    at main.js:1:16283
```

When I run `npm run serve` the `Error: Your browser does not support WebGPU` message is displayed and the developer console says `[HMR] Waiting for update signal from WDS...` - the WebGPU canvas is not shown.

Perhaps this is due to Windows 10, but would be nice to know what system it works on as Chrome and Safari currently do not support WebGPU on my M1 Mac.

**Comment by neurolabusc** [comment]
I was able to get the demo running an a M2 MacBook by installing Chrome Canary. With this system, everything works out of the box. I guess we need to temper our compatibility expectations for this new API on older machines.

**Comment by Twinklebear** [comment]
Thanks Chris, I think this issue is just that the Chrome release (112) hasn't updated the API from `compilationInfo` to `getCompilationInfo`. In Chrome Beta (113) and Chrome Canary, the app runs. I'm usually testing WebGPU in Chrome Canary so I didn't notice this broke the demo on Chrome stable. I'll leave it as is, since otherwise it'll just break when Chrome Beta gets promoted and the name change happens.

I think it should run on your older system as well, but you'd just need to use Chrome Beta or Chrome Canary.

**Comment by Twinklebear** [comment]
I should also note, I'm testing this on an M1 Mac Mini
